# Basic
title: Jiang wenqiang
subtitle: A blog for Jiang wenqiang
welcome_message: <a href="https://github.com/jiangwqcooler" target="_blank">visit my github</a>
description: A girl surnamed li laugh at my Engilsh, so ,my blob must write in English, AUGMENT!AUGMENT!AUGMENT!  
creator: <a href="www.jiangwq.me">@Mr. Jiang</a>

url: "http://www.jiangwq.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Jiang wenqiang
    # duoshuo: 
    
# Social
social:
    weibo: no
    github: no
    twitter: no
    gplus: 107108267983477358170
    mail: 360920474@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
